apiVersion: v1
kind: Pod
metadata:
  name: redis

spec:
  containers:
  - name: "redis"
    image: "redis"

//note about yml don't use tab instead use double-space for spacing the elements in the yml file.
