apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-11-23T08:05:56Z"
  labels:
    name: webapp-pod
  name: webapp-pod
  namespace: default
  resourceVersion: "1500"
  uid: e7b531ed-c929-44ed-a0f5-6f32b900d4ef
spec:
  containers:
  - envFrom:
    - secretRef:
        name: db-secret
    image: kodekloud/simple-webapp-mysql
    imagePullPolicy: Always
    name: webapp
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File