apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-11-12T03:09:46Z"
  name: elephant
  namespace: default
  resourceVersion: "990"
  uid: 827d9cad-06d5-458a-ba10-b91f30da6b92
spec:
  containers:
  - args:
    - --vm
    - "1"
    - --vm-bytes
    - 15M
    - --vm-hang
    - "1"
    command:
    - stress
    image: polinux/stress
    imagePullPolicy: Always
    name: mem-stress
    resources:
      limits:
        memory: 20Mi
      requests:
        memory: 5Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-qbj7t
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: controlplane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-qbj7t
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-11-12T03:09:48Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-11-12T03:09:46Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-11-12T03:09:46Z"
    message: 'containers with unready status: [mem-stress]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-11-12T03:09:46Z"
    message: 'containers with unready status: [mem-stress]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-11-12T03:09:46Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://b2928fc537a7f45c193a56d61ebfda9e792adf4a523b3f135303de2520b02922
    image: docker.io/polinux/stress:latest
    imageID: docker.io/polinux/stress@sha256:b6144f84f9c15dac80deb48d3a646b55c7043ab1d83ea0a697c09097aaad21aa
    lastState:
      terminated:
        containerID: containerd://6c0f1e7116d0fd43d7cf6232f35a3f96d7432663182f50b437053f490b39ce9f
        exitCode: 1
        finishedAt: "2024-11-12T03:10:31Z"
        reason: OOMKilled
        startedAt: "2024-11-12T03:10:31Z"
    name: mem-stress
    ready: false
    restartCount: 4
    started: false
    state:
      terminated:
        containerID: containerd://b2928fc537a7f45c193a56d61ebfda9e792adf4a523b3f135303de2520b02922
        exitCode: 1
        finishedAt: "2024-11-12T03:11:25Z"
        reason: OOMKilled
        startedAt: "2024-11-12T03:11:24Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-qbj7t
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.187.79
  hostIPs:
  - ip: 192.168.187.79
  phase: Running
  podIP: 10.42.0.10
  podIPs:
  - ip: 10.42.0.10
  qosClass: Burstable
  startTime: "2024-11-12T03:09:46Z"