apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: default
spec:
  ports:
  - nodePort: 30080
    port: 8080
    targetPort: 8080
  selector:
    name: simple-webapp
  type: NodePort

# apiVersion: v1
# kind: Service
# metadata:
#   creationTimestamp: null
#   labels:
#     app: webapp-service
#   name: webapp-service
# spec:
#   ports:
#   - name: "8080"
#     nodePort: 30080
#     port: 8080
#     protocol: TCP
#     targetPort: 8080
#   selector:
#     name: simple-webapp
#     app: webapp-service
#   type: NodePort
# status:
#   loadBalancer: {}