#       EphemeralContainers: nil,
#       RestartPolicy:       "Always",
#       ... // 28 identical fields
#   }

#
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-12-04T01:45:03Z"
  name: ubuntu-sleeper
  namespace: default
  resourceVersion: "845"
  uid: 582ec84d-c428-44e9-8aee-4952a993db97
spec:
  containers:
  - command:
    - sleep
    - "4800"
    image: ubuntu
    securityContext:
      runAsUser: 1010
      capabailites:
        add:
        - SYS_TIME
        - NET_ADMIN
    imagePullPolicy: Always
    name: ubuntu
    resources: {}